language: rust
rust:
  - nightly

before_script: |
  rustup update stable &&
  rustup component add --toolchain stable rustfmt-preview &&
  rustup component add --toolchain stable clippy-preview
script: |
  cargo +stable fmt -- --check &&
  cargo +stable clippy -- -D clippy::all &&
  cargo build --verbose &&
  cargo test  --verbose
cache: cargo